apiVersion: apps/v1
kind: Deployment
metadata:
  name: monu-deployment
  labels:
    app: monu
spec:
  replicas: 1
  selector:
    matchLabels:
      app: monu
  template:
    metadata:
      labels:
        app: monu
    spec:
      containers:
      - name: monu
        image: sreenuadr/dockertest
        ports:
        - containerPort: 8080